server:
  port: 8099

spring:  application:    name: web
#  mvc
    
#  static resources locations  
#  resources:
#    static-locations:
#    - 
#  映射为mvc的静态资源模式
#  mvc:
#    static-path-pattern: /static/**
    
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    
  thymeleaf:
    enabled: true
    cache: false
#    check-template: true
#    check-template-location: true
    mode: HTML5
#    prefix: classpath:templates/
#    suffix: .html
#    encoding: UTF-8
#    template-resolver-order: 0
    servlet:
      content-type: text/html

eureka: 
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true
  instance:
    prefer-ip-address: true

#feign:
#  compression:
#    request:
#      enabled: logging:
  level:
    org: 
      zero: debug
        
    