server:
  port: 8099

spring:  application:    name: web
    
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    
  thymeleaf:
    enabled: true
    cache: false
    check-template: true
    check-template-location: true
    mode: HTML5
    prefix: classpath:templates/
    template-resolver-order: 0
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html

eureka: 
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true
  instance:
    prefer-ip-address: true