server:
  port: 8091

spring:  application:    name: customer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.115.170.102:3306/test?useUnicode=true\
            &characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: test
      password: 123

mybatis:
  mapper-locations:  - classpath:org/zero/customer/mapper/mapping/*.xml