package org.zero.customer.service.mapper;

import java.util.List;

import org.zero.customer.model.CCustInfo;
import org.zero.customer.model.CCustInfoVo;

public interface CCustInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cust_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer custId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cust_info
     *
     * @mbg.generated
     */
    int insert(CCustInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cust_info
     *
     * @mbg.generated
     */
    int insertSelective(CCustInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cust_info
     *
     * @mbg.generated
     */
    CCustInfo selectByPrimaryKey(Integer custId);
    
    CCustInfo selectByCert(String certNo);
    
    List<CCustInfo> selectByColumn(CCustInfo custInfo);
    
    List<CCustInfoVo> selectExtendByColumn(CCustInfoVo custInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cust_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CCustInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cust_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CCustInfo record);
}