package org.zero.customer.service.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.zero.customer.model.CCustBank;
import org.zero.customer.model.CCustBankVo;

public interface CCustBankMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table c_cust_bank
	 *
	 * @mbg.generated Mon Jun 15 18:01:06 CST 2020
	 */
	int deleteByPrimaryKey(Integer bankId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table c_cust_bank
	 *
	 * @mbg.generated Mon Jun 15 18:01:06 CST 2020
	 */
	int insert(CCustBank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table c_cust_bank
	 *
	 * @mbg.generated Mon Jun 15 18:01:06 CST 2020
	 */
	int insertSelective(CCustBank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table c_cust_bank
	 *
	 * @mbg.generated Mon Jun 15 18:01:06 CST 2020
	 */
	CCustBank selectByPrimaryKey(Integer bankId);

	CCustBank selectByUnique(@Param("custId") Integer custId, @Param("bankCode") String bankCode);
	
	List<CCustBankVo> selectVoByColumn(CCustBankVo custBankVo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table c_cust_bank
	 *
	 * @mbg.generated Mon Jun 15 18:01:06 CST 2020
	 */
	int updateByPrimaryKeySelective(CCustBank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table c_cust_bank
	 *
	 * @mbg.generated Mon Jun 15 18:01:06 CST 2020
	 */
	int updateByPrimaryKey(CCustBank record);
}