package org.zero.customer.model;

import java.time.LocalDate;
import java.util.Date;

/**
 * Database Table Remarks:
 *   客户信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table c_cust_info
 */
public class CCustInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.cust_id
     *
     * @mbg.generated
     */
    private Integer custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.cert_no
     *
     * @mbg.generated
     */
    private String certNo;

    /**
     * Database Column Remarks:
     *   L-大陆、O-其他
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.CERT_AREA
     *
     * @mbg.generated
     */
    private String certArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.cust_type
     *
     * @mbg.generated
     */
    private String custType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.already_auth
     *
     * @mbg.generated
     */
    private Byte alreadyAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.birth
     *
     * @mbg.generated
     */
    private LocalDate birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.risk_evaluat_score
     *
     * @mbg.generated
     */
    private Integer riskEvaluatScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.is_staff
     *
     * @mbg.generated
     */
    private Byte isStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.introducer
     *
     * @mbg.generated
     */
    private String introducer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.default_bank
     *
     * @mbg.generated
     */
    private Integer defaultBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.cust_id
     *
     * @return the value of c_cust_info.cust_id
     *
     * @mbg.generated
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.cust_id
     *
     * @param custId the value for c_cust_info.cust_id
     *
     * @mbg.generated
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.account_id
     *
     * @return the value of c_cust_info.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.account_id
     *
     * @param accountId the value for c_cust_info.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.real_name
     *
     * @return the value of c_cust_info.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.real_name
     *
     * @param realName the value for c_cust_info.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.cert_no
     *
     * @return the value of c_cust_info.cert_no
     *
     * @mbg.generated
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.cert_no
     *
     * @param certNo the value for c_cust_info.cert_no
     *
     * @mbg.generated
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.CERT_AREA
     *
     * @return the value of c_cust_info.CERT_AREA
     *
     * @mbg.generated
     */
    public String getCertArea() {
        return certArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.CERT_AREA
     *
     * @param certArea the value for c_cust_info.CERT_AREA
     *
     * @mbg.generated
     */
    public void setCertArea(String certArea) {
        this.certArea = certArea == null ? null : certArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.cust_type
     *
     * @return the value of c_cust_info.cust_type
     *
     * @mbg.generated
     */
    public String getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.cust_type
     *
     * @param custType the value for c_cust_info.cust_type
     *
     * @mbg.generated
     */
    public void setCustType(String custType) {
        this.custType = custType == null ? null : custType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.already_auth
     *
     * @return the value of c_cust_info.already_auth
     *
     * @mbg.generated
     */
    public Byte getAlreadyAuth() {
        return alreadyAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.already_auth
     *
     * @param alreadyAuth the value for c_cust_info.already_auth
     *
     * @mbg.generated
     */
    public void setAlreadyAuth(Byte alreadyAuth) {
        this.alreadyAuth = alreadyAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.birth
     *
     * @return the value of c_cust_info.birth
     *
     * @mbg.generated
     */
    public LocalDate getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.birth
     *
     * @param birth the value for c_cust_info.birth
     *
     * @mbg.generated
     */
    public void setBirth(LocalDate birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.gender
     *
     * @return the value of c_cust_info.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.gender
     *
     * @param gender the value for c_cust_info.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.risk_evaluat_score
     *
     * @return the value of c_cust_info.risk_evaluat_score
     *
     * @mbg.generated
     */
    public Integer getRiskEvaluatScore() {
        return riskEvaluatScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.risk_evaluat_score
     *
     * @param riskEvaluatScore the value for c_cust_info.risk_evaluat_score
     *
     * @mbg.generated
     */
    public void setRiskEvaluatScore(Integer riskEvaluatScore) {
        this.riskEvaluatScore = riskEvaluatScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.is_staff
     *
     * @return the value of c_cust_info.is_staff
     *
     * @mbg.generated
     */
    public Byte getIsStaff() {
        return isStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.is_staff
     *
     * @param isStaff the value for c_cust_info.is_staff
     *
     * @mbg.generated
     */
    public void setIsStaff(Byte isStaff) {
        this.isStaff = isStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.introducer
     *
     * @return the value of c_cust_info.introducer
     *
     * @mbg.generated
     */
    public String getIntroducer() {
        return introducer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.introducer
     *
     * @param introducer the value for c_cust_info.introducer
     *
     * @mbg.generated
     */
    public void setIntroducer(String introducer) {
        this.introducer = introducer == null ? null : introducer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.default_bank
     *
     * @return the value of c_cust_info.default_bank
     *
     * @mbg.generated
     */
    public Integer getDefaultBank() {
        return defaultBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.default_bank
     *
     * @param defaultBank the value for c_cust_info.default_bank
     *
     * @mbg.generated
     */
    public void setDefaultBank(Integer defaultBank) {
        this.defaultBank = defaultBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_info.create_time
     *
     * @return the value of c_cust_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_info.create_time
     *
     * @param createTime the value for c_cust_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

//	@Override
//	public int hashCode() {
//		return Objects.hash(values);
//	}

	@Override
	public String toString() {
		return "CCustInfo [custId=" + custId + ", accountId=" + accountId + ", realName=" + realName + ", certNo="
				+ certNo + ", certArea=" + certArea + ", custType=" + custType + ", alreadyAuth=" + alreadyAuth
				+ ", birth=" + birth + ", gender=" + gender + ", riskEvaluatScore=" + riskEvaluatScore + ", isStaff="
				+ isStaff + ", introducer=" + introducer + ", defaultBank=" + defaultBank + ", createTime=" + createTime
				+ "]";
	}
    
}