package org.zero.customer.model;

import java.util.Date;

import com.alibaba.fastjson.JSON;

/**
 * Database Table Remarks:
 *   客户账户表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table c_cust_account
 */
public class CCustAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_account.account_id
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_account.cust_id
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private Integer custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_account.phone_no
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_account.user_name
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_account.email
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_account.password
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_account.register_time
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private Date registerTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_account.account_id
     *
     * @return the value of c_cust_account.account_id
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_account.account_id
     *
     * @param accountId the value for c_cust_account.account_id
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_account.cust_id
     *
     * @return the value of c_cust_account.cust_id
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_account.cust_id
     *
     * @param custId the value for c_cust_account.cust_id
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_account.phone_no
     *
     * @return the value of c_cust_account.phone_no
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_account.phone_no
     *
     * @param phoneNo the value for c_cust_account.phone_no
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_account.user_name
     *
     * @return the value of c_cust_account.user_name
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_account.user_name
     *
     * @param userName the value for c_cust_account.user_name
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_account.email
     *
     * @return the value of c_cust_account.email
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_account.email
     *
     * @param email the value for c_cust_account.email
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_account.password
     *
     * @return the value of c_cust_account.password
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_account.password
     *
     * @param password the value for c_cust_account.password
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_account.register_time
     *
     * @return the value of c_cust_account.register_time
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_account.register_time
     *
     * @param registerTime the value for c_cust_account.register_time
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

	@Override
	public String toString() {
		return JSON.toJSONString(this);
	}
    
}