package org.zero.customer.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   客户银行卡信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table c_cust_bank
 */
public class CCustBank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_bank.bank_id
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private Integer bankId;

    /**
     * Database Column Remarks:
     *   客户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_bank.cust_id
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private Integer custId;

    /**
     * Database Column Remarks:
     *   开户银行信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_bank.bank_info
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private String bankInfo;

    /**
     * Database Column Remarks:
     *   银行卡号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_bank.bank_code
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private String bankCode;

    /**
     * Database Column Remarks:
     *   账户属性：B-银行卡、P-存折
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_bank.account_type
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private String accountType;

    /**
     * Database Column Remarks:
     *   开户行省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_bank.establish_province
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private String establishProvince;

    /**
     * Database Column Remarks:
     *   开户行市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_bank.establish_city
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private String establishCity;

    /**
     * Database Column Remarks:
     *   状态：E-启用、D-注销
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_bank.status
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private String status;

    /**
     * Database Column Remarks:
     *   默认使用：1-是、0-否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_bank.default_use
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private Byte defaultUse;

    /**
     * Database Column Remarks:
     *   第三方认证是否成功：1-成功、0-不成功
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_bank.already_auth
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private Byte alreadyAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_cust_bank.create_time
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_bank.bank_id
     *
     * @return the value of c_cust_bank.bank_id
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_bank.bank_id
     *
     * @param bankId the value for c_cust_bank.bank_id
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_bank.cust_id
     *
     * @return the value of c_cust_bank.cust_id
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_bank.cust_id
     *
     * @param custId the value for c_cust_bank.cust_id
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_bank.bank_info
     *
     * @return the value of c_cust_bank.bank_info
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public String getBankInfo() {
        return bankInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_bank.bank_info
     *
     * @param bankInfo the value for c_cust_bank.bank_info
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setBankInfo(String bankInfo) {
        this.bankInfo = bankInfo == null ? null : bankInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_bank.bank_code
     *
     * @return the value of c_cust_bank.bank_code
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_bank.bank_code
     *
     * @param bankCode the value for c_cust_bank.bank_code
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_bank.account_type
     *
     * @return the value of c_cust_bank.account_type
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_bank.account_type
     *
     * @param accountType the value for c_cust_bank.account_type
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_bank.establish_province
     *
     * @return the value of c_cust_bank.establish_province
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public String getEstablishProvince() {
        return establishProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_bank.establish_province
     *
     * @param establishProvince the value for c_cust_bank.establish_province
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setEstablishProvince(String establishProvince) {
        this.establishProvince = establishProvince == null ? null : establishProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_bank.establish_city
     *
     * @return the value of c_cust_bank.establish_city
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public String getEstablishCity() {
        return establishCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_bank.establish_city
     *
     * @param establishCity the value for c_cust_bank.establish_city
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setEstablishCity(String establishCity) {
        this.establishCity = establishCity == null ? null : establishCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_bank.status
     *
     * @return the value of c_cust_bank.status
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_bank.status
     *
     * @param status the value for c_cust_bank.status
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_bank.default_use
     *
     * @return the value of c_cust_bank.default_use
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public Byte getDefaultUse() {
        return defaultUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_bank.default_use
     *
     * @param defaultUse the value for c_cust_bank.default_use
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setDefaultUse(Byte defaultUse) {
        this.defaultUse = defaultUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_bank.already_auth
     *
     * @return the value of c_cust_bank.already_auth
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public Byte getAlreadyAuth() {
        return alreadyAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_bank.already_auth
     *
     * @param alreadyAuth the value for c_cust_bank.already_auth
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setAlreadyAuth(Byte alreadyAuth) {
        this.alreadyAuth = alreadyAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cust_bank.create_time
     *
     * @return the value of c_cust_bank.create_time
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cust_bank.create_time
     *
     * @param createTime the value for c_cust_bank.create_time
     *
     * @mbg.generated Mon Jun 15 18:01:06 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}