server:
  port: 8091

spring:  application:    name: customer
    
  jackson:
    default-property-inclusion: non-null
  datasource:
#    druid:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.170.102:3306/test?useUnicode=true\
            &characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true 
    username: test
    password: 123
    
# 官方正在调试ribbon loadbalance，建议使用spring cloud balancer
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

mybatis:
#  type-handlers-package: org.apache.ibatis.type
#  type-a
  mapper-locations:#  - classpath:org.zero.customer.mapper.mapping.*.xml
  - classpath:org/zero/customer/mapper/mapping/*.xml
  
eureka: 
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true
  instance:
    prefer-ip-address: true