package org.zero.user.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   部门信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table u_department
 */
public class UDepartment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_department.dept_code
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_department.dept_name
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_department.parent_dept
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    private String parentDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_department.dept_leader
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    private String deptLeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_department.creator
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_department.create_time
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_department.enabled
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_department.dept_code
     *
     * @return the value of u_department.dept_code
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_department.dept_code
     *
     * @param deptCode the value for u_department.dept_code
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_department.dept_name
     *
     * @return the value of u_department.dept_name
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_department.dept_name
     *
     * @param deptName the value for u_department.dept_name
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_department.parent_dept
     *
     * @return the value of u_department.parent_dept
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public String getParentDept() {
        return parentDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_department.parent_dept
     *
     * @param parentDept the value for u_department.parent_dept
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public void setParentDept(String parentDept) {
        this.parentDept = parentDept == null ? null : parentDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_department.dept_leader
     *
     * @return the value of u_department.dept_leader
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public String getDeptLeader() {
        return deptLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_department.dept_leader
     *
     * @param deptLeader the value for u_department.dept_leader
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public void setDeptLeader(String deptLeader) {
        this.deptLeader = deptLeader == null ? null : deptLeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_department.creator
     *
     * @return the value of u_department.creator
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_department.creator
     *
     * @param creator the value for u_department.creator
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_department.create_time
     *
     * @return the value of u_department.create_time
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_department.create_time
     *
     * @param createTime the value for u_department.create_time
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_department.enabled
     *
     * @return the value of u_department.enabled
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_department.enabled
     *
     * @param enabled the value for u_department.enabled
     *
     * @mbg.generated Tue Jun 30 14:26:41 CST 2020
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}