package org.zero.user.model;

import com.alibaba.fastjson.JSON;

/**
 * Database Table Remarks:
 *   操作权限信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table u_operate_permission
 */
public class UOperatePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_operate_permission.permission_code
     *
     * @mbg.generated Tue Jun 30 11:36:56 CST 2020
     */
    private String permissionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_operate_permission.permission_name
     *
     * @mbg.generated Tue Jun 30 11:36:56 CST 2020
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_operate_permission.permission_url
     *
     * @mbg.generated Tue Jun 30 11:36:56 CST 2020
     */
    private String permissionUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_operate_permission.enabled
     *
     * @mbg.generated Tue Jun 30 11:36:56 CST 2020
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_operate_permission.permission_code
     *
     * @return the value of u_operate_permission.permission_code
     *
     * @mbg.generated Tue Jun 30 11:36:56 CST 2020
     */
    public String getPermissionCode() {
        return permissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_operate_permission.permission_code
     *
     * @param permissionCode the value for u_operate_permission.permission_code
     *
     * @mbg.generated Tue Jun 30 11:36:56 CST 2020
     */
    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode == null ? null : permissionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_operate_permission.permission_name
     *
     * @return the value of u_operate_permission.permission_name
     *
     * @mbg.generated Tue Jun 30 11:36:56 CST 2020
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_operate_permission.permission_name
     *
     * @param permissionName the value for u_operate_permission.permission_name
     *
     * @mbg.generated Tue Jun 30 11:36:56 CST 2020
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_operate_permission.permission_url
     *
     * @return the value of u_operate_permission.permission_url
     *
     * @mbg.generated Tue Jun 30 11:36:56 CST 2020
     */
    public String getPermissionUrl() {
        return permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_operate_permission.permission_url
     *
     * @param permissionUrl the value for u_operate_permission.permission_url
     *
     * @mbg.generated Tue Jun 30 11:36:56 CST 2020
     */
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl == null ? null : permissionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_operate_permission.enabled
     *
     * @return the value of u_operate_permission.enabled
     *
     * @mbg.generated Tue Jun 30 11:36:56 CST 2020
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_operate_permission.enabled
     *
     * @param enabled the value for u_operate_permission.enabled
     *
     * @mbg.generated Tue Jun 30 11:36:56 CST 2020
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

	@Override
	public String toString() {
		return JSON.toJSONString(this);
	}
    
}