package org.zero.user.model;

/**
 * Database Table Remarks:
 *   权限信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table u_permission
 */
public class UPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_permission.permission_code
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    private String permissionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_permission.permission_name
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_permission.permission_type
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    private String permissionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_permission.permission_url
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    private String permissionUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_permission.parent_permission
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    private String parentPermission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_permission.status
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_permission.permission_code
     *
     * @return the value of u_permission.permission_code
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    public String getPermissionCode() {
        return permissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_permission.permission_code
     *
     * @param permissionCode the value for u_permission.permission_code
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode == null ? null : permissionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_permission.permission_name
     *
     * @return the value of u_permission.permission_name
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_permission.permission_name
     *
     * @param permissionName the value for u_permission.permission_name
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_permission.permission_type
     *
     * @return the value of u_permission.permission_type
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    public String getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_permission.permission_type
     *
     * @param permissionType the value for u_permission.permission_type
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    public void setPermissionType(String permissionType) {
        this.permissionType = permissionType == null ? null : permissionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_permission.permission_url
     *
     * @return the value of u_permission.permission_url
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    public String getPermissionUrl() {
        return permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_permission.permission_url
     *
     * @param permissionUrl the value for u_permission.permission_url
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl == null ? null : permissionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_permission.parent_permission
     *
     * @return the value of u_permission.parent_permission
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    public String getParentPermission() {
        return parentPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_permission.parent_permission
     *
     * @param parentPermission the value for u_permission.parent_permission
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    public void setParentPermission(String parentPermission) {
        this.parentPermission = parentPermission == null ? null : parentPermission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_permission.status
     *
     * @return the value of u_permission.status
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_permission.status
     *
     * @param status the value for u_permission.status
     *
     * @mbg.generated Mon Jun 29 15:29:42 CST 2020
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}