package org.zero.user.service.mapper;

import java.util.List;

import org.zero.user.model.UDepartment;

public interface UDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_department
     *
     * @mbg.generated Mon Jun 29 15:25:48 CST 2020
     */
    int deleteByPrimaryKey(String deptCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_department
     *
     * @mbg.generated Mon Jun 29 15:25:48 CST 2020
     */
    int insert(UDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_department
     *
     * @mbg.generated Mon Jun 29 15:25:48 CST 2020
     */
    int insertSelective(UDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_department
     *
     * @mbg.generated Mon Jun 29 15:25:48 CST 2020
     */
    UDepartment selectByPrimaryKey(String deptCode);
    
    List<UDepartment> selectByColumn(UDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_department
     *
     * @mbg.generated Mon Jun 29 15:25:48 CST 2020
     */
    int updateByPrimaryKeySelective(UDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_department
     *
     * @mbg.generated Mon Jun 29 15:25:48 CST 2020
     */
    int updateByPrimaryKey(UDepartment record);
}