package org.zero.user.service.mapper;

import java.util.List;

import org.zero.user.model.UMenuInfo;

public interface UMenuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_menu_info
     *
     * @mbg.generated Tue Jun 30 11:36:44 CST 2020
     */
    int deleteByPrimaryKey(String permissionCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_menu_info
     *
     * @mbg.generated Tue Jun 30 11:36:44 CST 2020
     */
    int insert(UMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_menu_info
     *
     * @mbg.generated Tue Jun 30 11:36:44 CST 2020
     */
    int insertSelective(UMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_menu_info
     *
     * @mbg.generated Tue Jun 30 11:36:44 CST 2020
     */
    UMenuInfo selectByPrimaryKey(String permissionCode);
    
    List<UMenuInfo> selectByColumn(UMenuInfo record);
    
    List<UMenuInfo> selectByUser(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_menu_info
     *
     * @mbg.generated Tue Jun 30 11:36:44 CST 2020
     */
    int updateByPrimaryKeySelective(UMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_menu_info
     *
     * @mbg.generated Tue Jun 30 11:36:44 CST 2020
     */
    int updateByPrimaryKey(UMenuInfo record);
}