package org.zero.user.service.mapper;

import java.util.List;

import org.zero.user.model.URole;

public interface URoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated Mon Jun 29 15:27:54 CST 2020
     */
    int deleteByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated Mon Jun 29 15:27:54 CST 2020
     */
    int insert(URole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated Mon Jun 29 15:27:54 CST 2020
     */
    int insertSelective(URole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated Mon Jun 29 15:27:54 CST 2020
     */
    URole selectByPrimaryKey(String roleCode);
    
    List<URole> selectByColumn(URole record);
    
    List<URole> findRestByUser(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated Mon Jun 29 15:27:54 CST 2020
     */
    int updateByPrimaryKeySelective(URole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated Mon Jun 29 15:27:54 CST 2020
     */
    int updateByPrimaryKey(URole record);
}