package org.zero.user.service.mapper;

import java.util.List;

import org.zero.user.model.URoleAuth;
import org.zero.user.model.URoleAuthKey;
import org.zero.user.model.URoleAuthVo;

public interface URoleAuthMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table u_role_permission
	 *
	 * @mbg.generated Mon Jun 29 16:06:27 CST 2020
	 */
	int deleteByPrimaryKey(URoleAuthKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table u_role_permission
	 *
	 * @mbg.generated Mon Jun 29 16:06:27 CST 2020
	 */
	int insert(URoleAuth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table u_role_permission
	 *
	 * @mbg.generated Mon Jun 29 16:06:27 CST 2020
	 */
	int insertSelective(URoleAuth record);
	
	int insertBatch(List<URoleAuth> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table u_role_permission
	 *
	 * @mbg.generated Mon Jun 29 16:06:27 CST 2020
	 */
	URoleAuth selectByPrimaryKey(URoleAuthKey key);

	List<URoleAuthVo> selectAuth(URoleAuthVo roleAuthVo);

	List<URoleAuthVo> selectNonAuth(URoleAuthVo roleAuthVo);

	List<URoleAuthVo> selectAuthMenu(URoleAuthVo roleAuthVo);

	List<URoleAuthVo> selectNonAuthMenu(URoleAuthVo roleAuthVo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table u_role_permission
	 *
	 * @mbg.generated Mon Jun 29 16:06:27 CST 2020
	 */
	int updateByPrimaryKeySelective(URoleAuth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table u_role_permission
	 *
	 * @mbg.generated Mon Jun 29 16:06:27 CST 2020
	 */
	int updateByPrimaryKey(URoleAuth record);
}