package org.zero.user.service.mapper;

import java.util.List;

import org.zero.user.model.UUserRole;
import org.zero.user.model.UUserRoleKey;
import org.zero.user.model.UUserRoleVo;

public interface UUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_role
     *
     * @mbg.generated Mon Jun 29 15:29:09 CST 2020
     */
    int deleteByPrimaryKey(UUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_role
     *
     * @mbg.generated Mon Jun 29 15:29:09 CST 2020
     */
    int insert(UUserRole record);
    
    int insertBatch(List<UUserRole> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_role
     *
     * @mbg.generated Mon Jun 29 15:29:09 CST 2020
     */
    int insertSelective(UUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_role
     *
     * @mbg.generated Mon Jun 29 15:29:09 CST 2020
     */
    UUserRole selectByPrimaryKey(UUserRoleKey key);
    
//    List<UUserRoleVo> findByColumn(UUserRoleVo userRoleVo);
    
	List<UUserRoleVo> selectAuth(UUserRoleVo userRoleVo);

	List<UUserRoleVo> selectNonAuth(UUserRoleVo userRoleVo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_role
     *
     * @mbg.generated Mon Jun 29 15:29:09 CST 2020
     */
    int updateByPrimaryKeySelective(UUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_user_role
     *
     * @mbg.generated Mon Jun 29 15:29:09 CST 2020
     */
    int updateByPrimaryKey(UUserRole record);
}